name: todo_r
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  calendar_timeline: ^1.1.2
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  # the material Icons class.
  uses-material-design: true
